// agent/templates/svelte/arrow.svelte
<script lang="ts">
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { arrow } from "@funsaized/stet/svelte";
import "@funsaized/stet/style.css";
let destination: HTMLParagraphElement | undefined;
</script>

<p bind:this={destination}>Consequences of this action</p>
<!-- Wait for destination before mounting the action host. -->
{#if destination}
<button type="button" use:arrow={{ ...{"seed":42,"label":"Review this action."}, to: destination }}>Review action</button>
{/if}

// agent/templates/react/arrow.tsx
"use client";
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { useRef } from "react";
import { Arrow } from "@funsaized/stet/react";
import "@funsaized/stet/style.css";

export function AnnotatedAction({ enabled = true }: { enabled?: boolean }) {
  const target = useRef<HTMLButtonElement>(null);
  const destination = useRef<HTMLParagraphElement>(null);
  return <>
    <button ref={target} type="button">Review action</button>
    <p ref={destination}>Consequences of this action</p>
    {enabled && <Arrow from={target} to={destination} seed={42} label={"Review this action."} />}
  </>;
}
