// agent/templates/angular/arrow.ts
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { Component } from "@angular/core";
import { StetArrowDirective } from "@funsaized/stet/angular";
// Add @import "@funsaized/stet/style.css"; to the application's global stylesheet.
@Component({
  selector: "app-annotated-action",
  standalone: true,
  imports: [StetArrowDirective],
  template: `
    <p #destination>Consequences of this action</p>
    <button type="button" [stetArrow]='{ to: destination, seed: 42, label: "Review this action.", labelOffsetY: -12 }'>Review action</button>
  `,
})
export class AnnotatedAction {}

// agent/templates/react/arrow.tsx
"use client";
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { useRef } from "react";
import { Arrow } from "@funsaized/stet/react";
import "@funsaized/stet/style.css";

export function AnnotatedAction({ enabled = true }: { enabled?: boolean }) {
  const target = useRef<HTMLButtonElement>(null);
  const destination = useRef<HTMLParagraphElement>(null);
  return <>
    <button ref={target} type="button">Review action</button>
    <p ref={destination}>Consequences of this action</p>
    {enabled && <Arrow from={target} to={destination} seed={42} label={"Review this action."} labelOffsetY={-12} />}
  </>;
}
