// agent/templates/angular/sticky.ts
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { Component } from "@angular/core";
import type { StetHandle } from "@funsaized/stet";
import { StetStickyDirective } from "@funsaized/stet/angular";
// Add @import "@funsaized/stet/style.css"; to the application's global stylesheet.
@Component({
  selector: "app-annotated-action",
  standalone: true,
  imports: [StetStickyDirective],
  template: `
    <button type="button" [stetSticky]='{"seed":42,"text":"Review the consequences before continuing.","offsetY":8}' [stetOnHandle]="onHandle">Review action</button>
  `,
})
export class AnnotatedAction {
  handle: StetHandle | null = null;
  readonly onHandle = (next: StetHandle | null) => { this.handle = next; };
}

// agent/templates/svelte/sticky.svelte
<script lang="ts">
// Adapt these sample elements to existing source; retain their semantics and handlers.
import { sticky } from "@funsaized/stet/svelte";
import type { StetHandle } from "@funsaized/stet";
import "@funsaized/stet/style.css";
let handle: StetHandle | null = null;
const onHandle = (next: StetHandle | null) => { handle = next; };
</script>

<button type="button" use:sticky={{ ...{"seed":42,"text":"Review the consequences before continuing.","offsetY":8}, onHandle }}>Review action</button>
